[package]
name = "load-balancer"
version = "0.1.0"
edition = "2018"

# Add your other package metadata here

[dependencies]
actix-web = "3.4"
log = "0.4"
env_logger = "0.11"
rand = "0.8"
reqwest = "0.11"
serenity = "0.10"
sqlx = { version = "0.5", features = ["postgres"] }
prisma = "2.0.0-beta.x"

[dependencies.serde]
version = "1.0"
features = ["derive"]

# You can specify other dependencies as needed

[dependencies.functions]
# Specify the path to your functions module if needed
# path = "path-to-functions-module"
